name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pandas=2.1.3
  - pytest=7.0.0
  - scipy=1.14.0
  - pip=23.3.1
  - pip:
      - mlflow==2.18.0
      - wandb==0.12.17
