name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyyaml
  - hydra-core=1.3.2
  - pip=23.3.1
  - mlflow=2.12.1
  - scipy=1.14.0
  - pip:
      - wandb==0.12.17
      - databricks_cli==0.8.7
